# Generated by Django 3.2 on 2021-12-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agric_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
