# Generated by Django 3.2 on 2021-12-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agric_store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
